### PR TITLE
Do not reboot after updates are applied

### PR DESCRIPTION
**Pull request by alpe**
See:
https://coreos.com/os/docs/latest/update-strategies.html

### CODE REVIEW

**Comment by 5tefan** [comment]
> The off strategy is also straightforward. The update will be installed onto the passive partition and await a reboot command to complete the update. We don't recommend this strategy unless you reboot frequently as part of your normal operations workflow.

What's the rationale for `off` over `etcd-lock`?

**Comment by alpe** [comment]
I'd prefer `etcd-lock` as well but there are no local etcd instances running. I couldn't find any configuration options and took the same value as in Coreos [AWS templates](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/templates/cloud-config-worker#L4).
I thought local [etcd proxies](https://coreos.com/etcd/docs/latest/proxy.html) would be a good option to get that solved but I haven't found time to set them up.

**Comment by 5tefan** [comment]
Ah, that detail had left my working memory. One thing I read a lot when getting started was that Kubernetes (and CoreOS clusters) should have a dedicated etcd host/cluster. I don't completely understand the reason for this but I'm hypothesizing 1) to have dedicated resources for core cluster services to avoid competition with workloads or 2) for security reasons, "etcd is equivalent to root access to the cluster". Local etcd proxies sound good for situation 1, but less so for situation 2. 

I'm ok with merging this as our current solution. If we do merge, we should probably make an issue until someone can look into this more.

**Comment by alpe** [comment]
"Your etcd cluster will be heavily utilized since all objects storing within and every scheduling decision is recorded. It's recommended that you run a multi-machine cluster on dedicated hardware (with fast disks) to gain maximum performance and reliability of this important part of your cluster."
https://coreos.com/kubernetes/docs/latest/getting-started.html

**Comment by alpe** [comment]
This is pending for a while, so I'll close this now. It's not a big thing anyway.

**Pull request closed without merging**
