### PR TITLE
Fixes #14, setopts appropriately if in a zsh shell

### LINKED ISSUE #14: `BASH_REMATCH` doesn't work well with `zsh`
See: https://github.com/hermanjunge/kubernetes-digitalocean-terraform/blob/master/setup_terraform.sh#L10

The previous condition worked better for me. I'm on OSX

### PR DESCRIPTION
**Pull request by 5tefan**
@alpe, I tested locally, but would you confirm if this fixes #14 for you?

### CODE REVIEW

**Comment by alpe** [comment]
@5tefan I've tried something similar, too but this will break my prompt ([zprezto](https://github.com/sorin-ionescu/prezto): [peepcode](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_peepcode_setup) )

```
prompt_peepcode_precmd:2: bad output format specification
prompt_peepcode_precmd:7: bad output format specification
```

**Comment by 5tefan** [comment]
Hmm, my guess would be that our `setopt KSH_ARRAYS` is conflicting with their [`unsetopt KSH_ARRAYS`](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_peepcode_setup#L27) and messing up the array indexing in `prompt_peepcode_precmd`. 

Maybe we need to isolate the scope and use something like [LOCAL_OPTIONS](http://zsh.sourceforge.net/Doc/Release/Options.html#index-LOCALOPTIONS)?

**Comment by 5tefan** [comment]
@alpe, would you let me know if this works now?

**Comment by alpe** [comment]
@5tefan 👍

**Pull request merged**
